### PR TITLE
Correct types for a number of source files

### PR DESCRIPTION
**Pull request by jugglinmike**
There are still more source files to be corrected, but I'm submitting corrections to these files now as a way to amortize the review process and reduce conflicts with upcoming feature work.

### CODE REVIEW

**Review by gnarf — APPROVED** [review]
Read over, nothing standing out to me!

**Comment by gnarf** [comment]
I'm sure you saw these errors in the build task, but:

> ERROR: Unable to parse a tag's type expression for source file /home/runner/work/aria-at-automation-harness/aria-at-automation-harness/src/agent/cli.js in line 166 with tag title "param" and text "{import("events").EventEmitter} options.signals": Invalid type expression "import("events").EventEmitter": Expected "!", "=", "?", "[]", "|", or end of input but "(" found.

**Comment by jugglinmike** [comment]
Yeah, it seems like [JSDoc doesn't recognize the TypeScript "import" syntax for types](https://github.com/jsdoc/jsdoc/issues/1645). I can think of two options:

- take on [the "better-docs" project](https://github.com/SoftwareBrothers/better-docs#typedefimport) as a dependency
- take on [the "jsdoc-tsimport-plugin" project](https://github.com/polyforest/jsdoc-tsimport-plugin/) as a dependency
- Stop building docs altogether

I'm leaning toward the third option for a few reasons:

- we have never published this project's API documentation and because it's an application rather than a library (so the audience for a rendered view of the information seems fairly limited)
- I'm sensitive to further complicating the project's tool chain, particularly when it involves third-party components which attempt to integrate two other dependencies

What do you think, @gnarf?

**Comment by jugglinmike** [comment]
I've reviewed the two packages which would allow us to keep JSDoc, and neither seem viable ([the "better-docs" project's solution is unacceptably primitive](https://github.com/SoftwareBrothers/better-docs#typedefimport), and the "jsdoc-tsimport-plugin" project is unmaintained). I've opened gh-43 to remove JSDoc entirely, though I'm still open to suggestion on this.

**Comment by gnarf** [comment]
I agree with the points in the other PR and merged it.  If we need to bring the docs back some day we can solve then

**Comment by jugglinmike** [comment]
Thanks, @gnarf!

**Pull request merged**
